### PR TITLE
Update event namings based on edX standard formats

### PR DESCRIPTION
**Pull request by kurtb**

### CODE REVIEW

**Comment by sarina** [comment]
The analytics team does prefer this format.

Quick question - why `office.mix` over `officemix`? Either is fine, I think we're just a bit uncertain as to why the separation.

**Comment by kurtb** [comment]
I went with office.mix over officemix mostly in case more Microsoft Office related events come in. So you could imagine office.word.xxxx, office.powerpoint.xxx, office.sway.xxxx, etc... Make sense?

**Comment by sarina** [comment]
@kurtb yeah that's kind of what I was assuming, but you know what they say when you assume! :grin: 

Thanks for the clarification - LGTM :+1:

**Comment by sarina** [comment]
Oh yeah and the slide events emissions looks great too

**Pull request merged**
